//
//  EditInteractor.swift
//  VIPToDo
//
//  Created by Seokho on 2020/09/08.
//  Copyright (c) 2020 Seokho. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditBusinessLogic {
	func showTitle()
	func update(request: Edit.Add.Request)
}

protocol EditDataStore {
	var defaultText: String? { get set }
	var selectedIndex: Int? { get set }
	var service: CoreDataService? { get set }
}

class EditInteractor: EditBusinessLogic, EditDataStore {
	
	var defaultText: String?
	var selectedIndex: Int?
	
	var service: CoreDataService? {
		didSet {
			guard let service = self.service else {
				preconditionFailure()
			}
			
			self.worker = EditWorker(service: service)
		}
	}
	
	var presenter: EditPresentationLogic?
	var worker: EditWorker?
	
	
	func showTitle() {
		let response = Edit.GetTitle.Response(title: defaultText)
		presenter?.presentTitle(response: response)
	}
	
	
	func update(request: Edit.Add.Request) {
		
		if let index = self.selectedIndex {
			self.updateData(index: index, request: request)
		} else {
			self.addData(request: request)
		}
	}
	
	func updateData(index: Int, request: Edit.Add.Request) {
		
		worker?.updateData(index: index, title: request.title) { result in
			switch result {
			case .success:
				self.presenter?.presentDismiss(response: Edit.Add.Response())
			case .failure(let error):
				self.presenter?.presentErrorAlert(response: Edit.ErrorData.Response(error: error))
			}
		}
		
	}
	
	func addData(request: Edit.Add.Request) {
		
		worker?.addData(title: request.title) { result in
			switch result {
			case .success:
				self.presenter?.presentDismiss(response: Edit.Add.Response())
			case .failure(let error):
				self.presenter?.presentErrorAlert(response: Edit.ErrorData.Response(error: error))
			}
		}
		
	}
	
	
}
