//
//  EditRouter.swift
//  VIPToDo
//
//  Created by Seokho on 2020/09/08.
//  Copyright (c) 2020 Seokho. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol EditRoutingLogic {
	func routeToMain()
}

protocol EditDataPassing {
	var dataStore: EditDataStore? { get }
}

class EditRouter: NSObject, EditRoutingLogic, EditDataPassing {

	
	weak var viewController: EditViewController?
	var dataStore: EditDataStore?
	
	
	func routeToMain() {
			
		DispatchQueue.main.async {
			self.viewController?.dismiss(animated: true) { [weak self] in
				self?.viewController?.delegate?.refresh()
			}
		}
		
	}
}
