//
//  EditModels.swift
//  VIPToDo
//
//  Created by Seokho on 2020/09/08.
//  Copyright (c) 2020 Seokho. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Edit {
	
	enum GetTitle {
		
		struct Request { }
		
		struct Response {
			var title: String?
		}
		
		struct ViewModel {
			
			struct DisPlayTitle {
				var title: String?
			}
			
			var disPlayTitle: DisPlayTitle
		}
	}
	
	enum ErrorData {
		struct Request { }
			
		struct Response {
			var error: CoreDataError
		}
		
		struct ViewModel {
			struct DisplayedError {
				var error: CoreDataError
			}
			
			var displayData: DisplayedError
		}
	}
	
	
	enum Update {
		struct Request {
			var title: String
		}
		struct Response { }
		struct ViewModel { }
	}
	
	enum VaildCheck {
		struct Request {
			var text: String?
		}
		
		struct Response {
			var isVaild: Bool
		}
		
		struct ViewModel {
			
			struct DisplayedBarButton {
				var isVaild: Bool
			}
			
			var displayButton: DisplayedBarButton
		}
		
	}
	
}
