//
//  EditViewController.swift
//  VIPToDo
//
//  Created by Seokho on 2020/09/08.
//  Copyright (c) 2020 Seokho. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditDisplayLogic: class {
	func displayTitle(viewModel: Edit.GetTitle.ViewModel)
	func displayErrorAlert(viewModel: Edit.ErrorData.ViewModel)
	func displayDismiss(viewModel: Edit.Update.ViewModel)
	func displayBarButton(viewModel: Edit.VaildCheck.ViewModel)
}

class EditViewController: BaseViewController {
	
	weak var delegate: AddDelegate?
	
	var interactor: EditBusinessLogic?
	var router: (NSObjectProtocol & EditRoutingLogic & EditDataPassing)?
	
	lazy var doneButtonItem = UIBarButtonItem(barButtonSystemItem: .done, target: self, action: #selector(addToDo))
	
	lazy var titleInput: UITextField = {
		let textField = UITextField()
		textField.autocorrectionType = .no
		textField.borderStyle = .roundedRect
		textField.font = .systemFont(ofSize: 16)
		textField.placeholder = "Anythine Input..."
		textField.textColor = .label
		textField.layer.borderColor = UIColor.black.cgColor
		textField.translatesAutoresizingMaskIntoConstraints = false
		textField.addTarget(self, action: #selector(self.textFieldDidChange(_:)), for: .editingChanged)
		return textField
	}()
	
	override init() {
		super.init()
		setup()
	}
	
	required init?(coder aDecoder: NSCoder) {
		fatalError()
	}
	
	override func viewDidLoad() {
		super.viewDidLoad()
		fetchTitle()
	}
	
	override func configureUI() {
		super.configureUI()
		
		self.view.addSubview(titleInput)
	}
	
	override func setupConstraints() {
		super.setupConstraints()
		
		NSLayoutConstraint.activate([
			titleInput.topAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.topAnchor, constant: 16),
			titleInput.leadingAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.leadingAnchor, constant: 16),
			titleInput.trailingAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.trailingAnchor, constant: -16),
		])
	}
	
	// MARK: Setup
	private func setup() {
		let viewController = self
		let interactor = EditInteractor()
		let presenter = EditPresenter()
		let router = EditRouter()
		viewController.interactor = interactor
		viewController.router = router
		interactor.presenter = presenter
		presenter.viewController = viewController
		router.viewController = viewController
		router.dataStore = interactor
	}
	
	private func fetchTitle() {
		let request = Edit.GetTitle.Request()
		self.interactor?.showTitle(request: request)
	}
	
	@objc
	func addToDo() {
		if let title = self.titleInput.text {
			let request = Edit.Update.Request(title: title)
			self.interactor?.update(request: request)
		}
	}
	
	@objc
	func textFieldDidChange(_ sender: UITextField) {
		let request = Edit.VaildCheck.Request(text: sender.text?.trimmingCharacters(in: .whitespaces))
		self.interactor?.isVaildData(request: request)
	}
	
}
extension EditViewController: EditDisplayLogic {
	
	func displayBarButton(viewModel: Edit.VaildCheck.ViewModel) {
		if viewModel.displayButton.isVaild {
			self.navigationItem.rightBarButtonItem = self.doneButtonItem
		} else {
			self.navigationItem.rightBarButtonItem = nil
		}
	}
	
	func displayErrorAlert(viewModel: Edit.ErrorData.ViewModel) {
		let alert = UIAlertController(title: "Error",
									  message: viewModel.displayData.error.localizedDescription,
									  preferredStyle: .alert)
		
		let okAction = UIAlertAction(title: "OK", style: .default)
		alert.addAction(okAction)
		self.present(alert, animated: true)
	}
	
	func displayDismiss(viewModel: Edit.Update.ViewModel) {
		self.router?.routeToMain()
	}

	func displayTitle(viewModel: Edit.GetTitle.ViewModel) {
		
		if let title = viewModel.disPlayTitle.title {
			self.title = "Edit"
			self.titleInput.text = title
			self.navigationItem.rightBarButtonItem = self.doneButtonItem
		} else {
			self.title = "Add"
			self.navigationItem.rightBarButtonItem = nil
		}
		
	}
	
}
